### ISSUE TITLE
Getting "ReferenceError: is is not defined" on startup

### ISSUE THREAD

**Issue by braibaud** [rodtoll/homebridge-wireless-sensor-tag#10]
Hello, 

I've just setup the plugin and I am getting this on startup:

[wireless-sensor-tag] Initializing wireless-sensor-tag platform...
ReferenceError: is is not defined
    at new WirelessTagPlatform (/volume1/homebridge/node_modules/homebridge-wireless-sensor-tag/index.js:25:1)
    at /volume1/homebridge/node_modules/homebridge/src/server.ts:473:40
    at Array.forEach (<anonymous>)
    at Server.loadPlatforms (/volume1/homebridge/node_modules/homebridge/src/server.ts:400:27)
    at Server.start (/volume1/homebridge/node_modules/homebridge/src/server.ts:176:29)

My config looks fine and I can login to my wirelesstag list on the web using the supplied credentials.

**Comment by kennethlinzj** [comment]
I'm having the same issue!

**Comment by markywarky** [comment]
+1

**Comment by rterbush** [comment]
As the error says in the logs:

On line 25 of /var/lib/homebridge/node_modules/homebridge-wireless-sensor-tag/index.js, there is a typo.

```is}```

Remove the ```is```

**Comment by markywarky** [comment]
Thanks @rterbush. Removed after working out how to access files in a docker container. (I'm no developer.)

Now I'm a step further, but this is in the logs:
```
[2/6/2023, 11:58:01 AM] [wireless-sensor-tag] Initializing wireless-sensor-tag platform...
[2/6/2023, 11:58:03 AM] [wireless-sensor-tag] Failed getting tag list
[2/6/2023, 11:58:03 AM] [wireless-sensor-tag] Completed getting devices. Result=false
[2/6/2023, 11:58:03 AM] [wireless-sensor-tag] Could not get tags, no accessories exposed
```

Not putting this on you, @rterbush.
Anyone out there getting any further?

**Comment by rterbush** [comment]
I'm seeing the same thing after getting this up and running @markywarky . Tagging @rodtoll here to see if we can get them to weigh in...

After the startup was successful, the plugin modified my config file to add a section for `_bridge`. It references a mac addr for the username which does not exist on my network and is not the mac addr of my tag manager, so a bit confused here.

![2023-02-09_07-02-55](https://user-images.githubusercontent.com/526416/217834705-74b3daa1-f147-4a23-9f7d-8693a406b338.png)

**Comment by rterbush** [comment]
It also appears that the v0.8 branch is slightly ahead of the master branch. I think until we can get @rodtoll to weigh in on this, I am unable to move this forward.

**Comment by braibaud** [comment]
> Thanks @rterbush. Removed after working out how to access files in a docker container. (I'm no developer.)
> 
> Now I'm a step further, but this is in the logs:
> 
> ```
> [2/6/2023, 11:58:01 AM] [wireless-sensor-tag] Initializing wireless-sensor-tag platform...
> [2/6/2023, 11:58:03 AM] [wireless-sensor-tag] Failed getting tag list
> [2/6/2023, 11:58:03 AM] [wireless-sensor-tag] Completed getting devices. Result=false
> [2/6/2023, 11:58:03 AM] [wireless-sensor-tag] Could not get tags, no accessories exposed
> ```
> 
> Not putting this on you, @rterbush. Anyone out there getting any further?

It does ring a bell. I "think" I've had the same issue while setting it up last year. I figured out one of my sensor had a name with accent characters. I simplified the names and it started working (replaced "é" by "e").

**Comment by rterbush** [comment]
Thanks for your comments @braibaud 

The tag naming is definitely not what is causing my problem. I would point more to the mystery _bridge I see in my configuration as the problem. Would also be interested to learn how to install from the 0.8 branch instead of master to give that a try. Copying individual files did not work and I suspect it is more of a dependency issue that needs to be resolved in order to use the 0.8 branch. Since I am new to Homebridge, I am not yet aware of how to install from another github branch.

**Comment by rterbush** [comment]
FWIW, I've taken a look at some of the other forks of this repo. There are a couple that have made some decent progress. 

In particular, these:

From @gurase: https://github.com/gurase/homebridge-wireless-sensor-tag
From @PlenipotentSS: https://github.com/PlenipotentSS/homebridge-wireless-sensor-tag

I've forked the @PlenipotentSS repo and have figured out how to install this by hand. It works and I now have sensors linked into my Homekit environment.

I am not yet clear on what it takes to update the Homebridge catalog to point to a working repo. If/When I figure that out I will try to at least get this to a place where it is usable and installable from the Homebridge UI. Any nudge toward what that requires will be appreciated.

**Comment by karlhsueh** [comment]
> FWIW, I've taken a look at some of the other forks of this repo. There are a couple that have made some decent progress.
> 
> In particular, these:
> 
> From @gurase: https://github.com/gurase/homebridge-wireless-sensor-tag From @PlenipotentSS: https://github.com/PlenipotentSS/homebridge-wireless-sensor-tag
> 
> I've forked the @PlenipotentSS repo and have figured out how to install this by hand. It works and I now have sensors linked into my Homekit environment.
> 
> I am not yet clear on what it takes to update the Homebridge catalog to point to a working repo. If/When I figure that out I will try to at least get this to a place where it is usable and installable from the Homebridge UI. Any nudge toward what that requires will be appreciated.

Wondering if it just requires publishing to npm registry and tagging it with the "homebridge-plugin" tag.

<img width="655" alt="image" src="https://user-images.githubusercontent.com/7528921/218894820-1f83f7cf-fb48-4363-bf59-6b9f0dfeb68e.png">
