### ISSUE TITLE
Crash handling error. statusCode is undefined.

### ISSUE THREAD

**Issue by jbolter** [rodtoll/homebridge-wireless-sensor-tag#2]
The plugin runs fine for several days and then I get this randomly...  Looks to be an issue in error handling.  Let me know if there is any other information I can provide.

[wireless-sensor-tag] Starting update of wireless tags from tag manager
[wireless-sensor-tag] Updated wireless tag data
[wireless-sensor-tag] Starting update of wireless tags from tag manager
[wireless-sensor-tag] Updated wireless tag data
[wireless-sensor-tag] Starting update of wireless tags from tag manager
/usr/local/lib/node_modules/homebridge-wireless-sensor-tag/index.js:67
        handleResult(response instanceof Error || response.statusCode != 200);
                                                          ^

TypeError: Cannot read property 'statusCode' of undefined
    at Request._callback (/usr/local/lib/node_modules/homebridge-wireless-sensor-tag/index.js:67:59)
    at self.callback (/usr/local/lib/node_modules/homebridge-wireless-sensor-tag/node_modules/request/request.js:198:22)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at Request.onRequestError (/usr/local/lib/node_modules/homebridge-wireless-sensor-tag/node_modules/request/request.js:820:8)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at Socket.socketErrorListener (_http_client.js:259:9)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at emitErrorNT (net.js:1257:8)
    at doNTCallback2 (node.js:441:9)
    at process._tickCallback (node.js:355:17)

**Comment by rodtoll** [comment]
@jbolter - Will fix. Thanks for pointing it out.

**Comment by Chioti** [comment]
I think I just got a very similar error:

/usr/local/lib/node_modules/homebridge-wireless-sensor-tag/index.js:67
        handleResult(response instanceof Error || response.statusCode != 200);
                                                          ^

TypeError: Cannot read property 'statusCode' of undefined
    at Request._callback (/usr/local/lib/node_modules/homebridge-wireless-sensor-tag/index.js:67:59)
    at self.callback (/usr/local/lib/node_modules/homebridge-wireless-sensor-tag/node_modules/request/request.js:198:22)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at Request.onRequestError (/usr/local/lib/node_modules/homebridge-wireless-sensor-tag/node_modules/request/request.js:820:8)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at Socket.socketErrorListener (_http_client.js:264:9)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at emitErrorNT (net.js:1256:8)
    at nextTickCallbackWith2Args (node.js:478:9)
    at process._tickCallback (node.js:392:17)

**Comment by rodtoll** [comment]
Good bug. The library isn't properly dealing with errors on querying the service. Adding to my worklist to fix. I'm hoping to crack the plugin the minute my new tag arrives. (I have one which supports humidity on the way).

**Comment by rodtoll** [comment]
I just published 0.0.2 which should address this issue. Feel free to re-open if you see it again.
